### ISSUE TITLE
The use of wildignore option will affect a lot things.

### ISSUE THREAD

**Issue by zoumi** [ZSaberLv0/ZFVimIgnore#1]
Because the wildignore option affect expand() function. So is it reasonable to make use of this option?
https://github.com/vim/vim/issues/8380

**Comment by ZSaberLv0** [comment]
* (recommended) `expand()` and `glob()` and similar functions has `nosuf` argument which let you ignore the `wildignore` option
* you may disable some of ignore result, see [FAQ](https://github.com/ZSaberLv0/ZFVimIgnore#faq)

    ``` vim
    function! s:myFilter(ignore)
        let i = len(a:ignore['dir']) - 1
        while i >= 0
            if a:ignore['dir'][i] == '.LfCache'
                call add(a:ignore['dir_filtered'], remove(a:ignore['dir'], i))
            endif
            let i -= 1
        endwhile
    endfunction
    
    if !exists('g:ZFIgnoreFilter')
        let g:ZFIgnoreFilter = {}
    endif
    let g:ZFIgnoreFilter['yourModuleName'] = function('s:myFilter')
    ```
